### ISSUE TITLE
[ Feature ] 대본으로 학습하기 스크린

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#12]
## 🛠 Issue

<img width="680" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/4644c59d-af12-4ede-a173-177d4fa3f400">

## 📝 To-do

- [x] 대본 리스트 스크린 구현
- [x] 대본 생성하기 스크린 구현
- [x] 대본 발음테스트 - 말이 제대로 들어가는지까지만 구현하고 이후 수정
