### ISSUE TITLE
[ Feature ] 추가된 대본 페이지 생성 및 파일 전송 테스트

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#20]
## 🛠 Issue

<img width="578" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/5af79dd0-ab23-403d-90cb-df78c588bc41">

## 📝 To-do

- [x] 대본 첫스크린 수정
- [x] 파일 녹음한거 사용할수 있게하기
- [ ] 파일 녹음과 실시간 텍스트 인식 동시에 실행하게 하기 (이부분 너무 오래걸려서 일단 녹음으로 디폴트 잡아놓고 이후에 수정하기)
- [x] 텍스트, 녹음파일 보내기 테스트 완료
- [x] 분석 스크린 생성
