### ISSUE TITLE
[ Feature ] 홈화면 연동 세팅 완료

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#25]
## 🛠 Issue
<img width="410" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/f2adcb33-59a0-4b30-9231-5d0be9a8bc57">

## 📝 To-do

- [x] 블러 디자인 수정
- [x] 맨위의 카드 더미데이터 세팅
- [x] 그래프 한달단위로 수정
- [x] 그래프 더미데이터 세팅
