### ISSUE TITLE
[ Feat ] 문단페이지 수정 및 생성

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#36]
## 🛠 Issue

<img width="416" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/12d8818d-7412-42d4-abd5-ff7190f69fb2">
<img width="406" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/4833343d-38cf-488d-9b43-b619aead8cd0">

## 📝 To-do

- [x] 사용자가 연습할 대본 채워넣고 스크린 생성
- [x] 해당 대본에 들어가면 대본 텍스트 찍여있는 두번째 스크린 생성
- [x] 결과페이지 확인 --> 가상 서버로 테스트해서 url만 넣으면 되게 세팅
