### ISSUE TITLE
[♻️ Refactor] 1.0 각 파트 버그 수정 및 마이그레이션 및 리펙토링

### ISSUE THREAD

**Issue by seochan99** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#53]
## 🛠 Issue

 희찬 파트 버그 수정 및 마이그레이션 및 리펙토링진행

## 📝 To-do

- [ ] 
- [ ] ├── bindings 
- [ ] │   └── root_binding.dart
- [ ] ├── firebase_options.dart
- [ ] ├── languages.dart
- [ ] ├── main.dart
- [ ] ├── main_app.dart
- [ ] ├── models
- [ ] │   ├── record_word_model.dart
- [ ] │   ├── user_word_model.dart
- [ ] │   ├── word_card_model.dart
- [ ] │   └── word_data_model.dart
- [ ] ├── providers
- [ ] │   └── temp
- [ ] ├── repositories
- [ ] │   └── temp
- [ ] ├── services
- [ ] │   └── auth
- [ ] │       └── auth_service.dart
- [ ] ├── utilities
- [x] │   ├── app_routes.dart
- [x] │   ├── base
- [x] │   │   └── supported_locale.dart
- [x] │   ├── style
- [x] │   │   └── color_styles.dart
- [x] │   └── validators
- [x] │       └── auth_validators.dart
- [x] ├── viewModels
- [x] │   ├── Paragraph
- [x] │   │   └── learning_session_screen_viewmodel.dart
- [ ] │   ├── auth
- [ ] │   │   ├── email_login_viewmodel.dart
- [ ] │   │   └── email_signup_viewmodel.dart
- [ ] │   ├── home
- [ ] │   │   └── home_viewmodel.dart
- [ ] │   ├── profile
- [ ] │   ├── record
- [ ] │   │   └── record_viewmodel.dart
- [ ] │   ├── root
- [ ] │   │   └── root_viewmodel.dart
- [x] │   ├── script
- [x] │   │   ├── analyze_viewmodel.dart
- [x] │   │   ├── create_script_viewmodel.dart
- [x] │   │   └── learning_session_screen_viewmodel.dart
- [ ] │   ├── study
- [ ] │   │   ├── date_study_screen_viewmodel.dart
- [x] │   │   └── study_viewmodel.dart
- [x] │   ├── user
- [x] │   │   └── user_viewmodel.dart
- [ ] │   └── word
- [ ] │       └── word_viewmodel.dart
- [ ] └── views
- [x]     ├── auth
- [x]     │   ├── auth_card_widget.dart
- [x]     │   ├── auth_dialog.dart
- [x]     │   ├── email_login_screen.dart
- [x]     │   ├── email_signup_screen.dart
- [x]     │   └── login_screen.dart
- [x]     ├── base
- [ ]     │   ├── base_screen.dart
- [ ]     │   ├── base_widget.dart
- [ ]     │   └── default_back_appbar.dart
- [ ]     ├── home
- [x]     │   ├── home_head_widget.dart
- [x]     │   ├── home_screen.dart
- [ ]     │   └── widget
- [x]     │       ├── bottom_widget.dart
- [ ]     │       ├── mid_widget.dart
- [x]     │       ├── study_chart.dart
- [ ]     │       └── top_widget.dart
- [x]     ├── paragraph
- [x]     │   ├── analyze_screen.dart
- [x]     │   ├── create_script_screen.dart
- [x]     │   └── learning_session_screen.dart
- [x]     ├── profile
- [x]     │   ├── profile_account
- [x]     │   │   └── profile_account_screen.dart
- [x]     │   ├── profile_divider_widget.dart
- [x]     │   ├── profile_header_widget.dart
- [x]     │   ├── profile_language_setting
- [x]     │   │   └── profile_language_setting.dart
- [x]     │   ├── profile_screen.dart
- [x]     │   ├── profile_setting_row_box_widget.dart
- [x]     │   └── profile_setting_row_btn_widget.dart
- [x]     ├── realtime
- [x]     │   └── real_create_script_screen.dart
- [ ]     ├── root
- [ ]     │   ├── custom_bottom_navigation_bar.dart
- [ ]     │   └── root_screen.dart
- [x]     ├── script
- [x]     │   ├── analyze_screen.dart
- [x]     │   ├── create_script_screen.dart
- [x]     │   ├── learning_session_screen.dart
- [x]     │   ├── user_script_screen.dart
- [x]     │   └── widget
- [x]     │       └── small_card.dart
- [ ]     ├── study
- [ ]     │   ├── date_study_screen.dart
- [ ]     │   ├── study_main.dart
- [ ]     │   └── widget
- [ ]     │       ├── contribution.dart
- [ ]     │       ├── study_card_widget.dart
- [ ]     │       ├── study_main_body_widget.dart
- [ ]     │       └── study_row_card_widget.dart
- [ ]     ├── test
- [ ]     │   └── test.dart
- [ ]     └── word
- [ ]         ├── widget
- [ ]         │   ├── blue_back_appbar.dart
- [ ]         │   ├── fail_word_dialog_widget.dart
- [ ]         │   ├── highlight_mistake_text_widget.dart
- [ ]         │   ├── sentence_alert_widget.dart
- [ ]         │   ├── sentence_guide_widget.dart
- [ ]         │   ├── sucess_word_dialog_widget.dart
- [ ]         │   ├── word_list_widget.dart
- [ ]         │   ├── word_result_dialog_widget.dart
- [ ]         │   ├── word_sentence_widget.dart
- [ ]         │   └── word_youtube_widget.dart
- [ ]         └── word_screen.dart

**Comment by seochan99** [comment]
<img width="534" alt="Screenshot 2024-04-07 at 9 16 59 PM" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/78739194/886f6f22-8ca0-48f4-9e89-e3df360b9767">

작업하시면서 위젯위에 /// 주석도 !
