### ISSUE TITLE
[ Fix ] 실시간 발음테스트 작동하도록 수정 및 리팩토링

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#54]
## 📝 To-do

- [x] 실시간 발음테스트 작동하도록 수정
- [x] 뒤로가기 하면 다시 연속해서 녹음안되는 문제 해결
- [x] MVVM모델로 구조 수정

**Comment by bunju20** [comment]
이제 대본스크린 수정이랑 비슷한 코드들 합치는 부분 시작합니다
