### ISSUE TITLE
[Fix] 대본학습 뷰, 뷰모델, 폴더 수정

### ISSUE THREAD

**Issue by bunju20** [GDSC-DGU/2024-SolutionChallenge-earlips-frontend#55]
## 🛠 Issue

<img width="435" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-earlips-frontend/assets/85238126/376f4bbc-4a8f-4fad-81a7-aa02d7f084c7">

## 📝 To-do

- [x] 뷰모델 병합 및 대본학습 뷰모델 수정
- [x] 대본학습 view 수정
- [x] 대본학습 view폴더 정리
